# coding: utf-8

# flake8: noqa

"""
    DigitalRooster

    Open API for Digital Rooster  # noqa: E501

    The version of the OpenAPI document: 0.8.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.alarms_api import AlarmsApi
from openapi_client.api.internet_radio_api import InternetRadioApi
from openapi_client.api.podcasts_api import PodcastsApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.alarm import Alarm
from openapi_client.models.error import Error
from openapi_client.models.podcast import Podcast
from openapi_client.models.station import Station

