# coding: utf-8

"""
    DigitalRooster

    Open API for Digital Rooster  # noqa: E501

    The version of the OpenAPI document: 0.8.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.podcast import Podcast  # noqa: E501
from openapi_client.rest import ApiException

class TestPodcast(unittest.TestCase):
    """Podcast unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Podcast
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.podcast.Podcast()  # noqa: E501
        if include_optional :
            return Podcast(
                uid = '0', 
                name = '0', 
                url = '0', 
                update_interval = 56
            )
        else :
            return Podcast(
                name = '0',
                url = '0',
        )

    def testPodcast(self):
        """Test Podcast"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
