# coding: utf-8

"""
    DigitalRooster

    Open API for Digital Rooster  # noqa: E501

    The version of the OpenAPI document: 0.8.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.internet_radio_api import InternetRadioApi  # noqa: E501
from openapi_client.rest import ApiException


class TestInternetRadioApi(unittest.TestCase):
    """InternetRadioApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.internet_radio_api.InternetRadioApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_streams_create(self):
        """Test case for streams_create

        Create a station info and add it to the list  # noqa: E501
        """
        pass

    def test_streams_delete(self):
        """Test case for streams_delete

        Delete Internet radio station from list  # noqa: E501
        """
        pass

    def test_streams_read_all(self):
        """Test case for streams_read_all

        Read all Internet radio streams  # noqa: E501
        """
        pass

    def test_streams_read_one(self):
        """Test case for streams_read_one

        Read one Internet radio station  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
