# coding: utf-8

"""
    DigitalRooster

    Open API for Digital Rooster  # noqa: E501

    The version of the OpenAPI document: 0.8.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.podcasts_api import PodcastsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPodcastsApi(unittest.TestCase):
    """PodcastsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.podcasts_api.PodcastsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_podcasts_create(self):
        """Test case for podcasts_create

        Add a podcast source with RSS feed and add it to the list  # noqa: E501
        """
        pass

    def test_podcasts_delete(self):
        """Test case for podcasts_delete

        Delete Podcast from list  # noqa: E501
        """
        pass

    def test_podcasts_read_all(self):
        """Test case for podcasts_read_all

        Read all podcast rss sources  # noqa: E501
        """
        pass

    def test_podcasts_read_one(self):
        """Test case for podcasts_read_one

        Read one Podcast identified by UUID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
