extraction:
  cpp:
    after_prepare:    # Customizable step used by all languages.
      - cmake --version
    configure:    # Customizable step used only by C/C++ extraction.
      command:
        - cmake -DCMAKE_BUILD_TYPE=Release -H$LGTM_SRC -B$LGTM_WORKSPACE -DBUILD_TESTS=Off -DTEST_COVERAGE=Off -DBUILD_GTEST_FROM_SRC=Off
    before_index:    # Customizable step used by all languages.
      - echo "before_index"
    index:    # Customizable step used by all languages.
      exclude:
        - libhwif/hardwarecontrol_stub.cpp
      build_command:
        - cmake --build $LGTM_WORKSPACE --parallel
