env:
  BUILD_DIR=/tmp/build
  SRC_DIR=/tmp/checkout
  
services:
  - docker

before_install:
  - docker pull ruschi/devlinuxqtquick2:latest
  - docker version
  - docker run -itd --name build_container ruschi/devlinuxqtquick2
  - docker exec build_container git clone https://github.com/truschival/DigitalRoosterGui.git $SRC_DIR

script:
  - docker exec build_container cmake -DCMAKE_BUILD_TYPE=Debug -H$SRC_DIR -B$BUILD_DIR -DBUILD_TESTS=On -DTEST_COVERAGE=On -DBUILD_GTEST_FROM_SRC=On
  - docker exec build_container cmake --build $BUILD_DIR --parallel
  
after_success:
  - docker exec build_container sh -c '
    cd /tmp/build;
    /tmp/build/bin/DigitalRooster_gtest ;
    lcov --directory . --capture --output-file coverage.info;
    lcov --remove coverage.info "/usr/*" --output-file coverage.info;
    lcov --remove coverage.info "*/GTestExternal/*" --output-file coverage.info;
    lcov --remove coverage.info "*/__/*" --output-file coverage.info;
    lcov --list coverage.info;'
  - docker exec build_container curl -o /tmp/codecov.sh https://codecov.io/bash
  - docker exec build_container chmod 755 /tmp/codecov.sh
  - docker exec -e BUILD_DIR=$BUILD_DIR -e SRC_DIR=$SRC_DIR -e CI -e TRAVIS=$TRAVIS -e TRAVIS_BRANCH=$TRAVIS_BRANCH -e TRAVIS_COMMIT=$TRAVIS_COMMIT -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG build_container /tmp/codecov.sh -s $BUILD_DIR -R $SRC_DIR -X gcov 

    
