sudo: required

env:
  BUILD_DIR=/tmp/build
  SRC_DIR=/tmp/checkout
  
services:
  - docker

before_install:
  - docker pull ruschi/devlinuxqtquick2:latest
  - docker run -itd --name build_container ruschi/devlinuxqtquick2
  - docker exec build_container python -m pip install cpp-coveralls
  - docker exec build_container git clone https://github.com/truschival/DigitalRoosterGui.git $SRC_DIR

script:
  - docker exec build_container cmake -DCMAKE_BUILD_TYPE=Debug -H$SRC_DIR -B$BUILD_DIR -DBUILD_TESTS=On -DTEST_COVERAGE=On -DBUILD_GTEST_FROM_SRC=On
  - docker exec build_container cmake --build $BUILD_DIR
  
after_success:
  - docker exec build_container sh -c '
    cd /tmp/build;
    /tmp/build/bin/DigitalRooster_gtest --gtest_filter=-Player*;
    lcov --directory . --capture --output-file coverage.info;
    lcov --remove coverage.info "/usr/*" --output-file coverage.info;
    lcov --remove coverage.info "*/GTestExternal/*" --output-file coverage.info;
    lcov --remove coverage.info "*/__/*" --output-file coverage.info;
    lcov --list coverage.info;
    cd /tmp/checkout;
    curl -o codecov.sh https://codecov.io/bash ;
    /bin/bash ./codecov.sh -s /tmp/build ; '
  - docker exec build_container sh -c 'cd /tmp/checkout; date; 
    /home/build/.local/bin/coveralls -r /tmp/checkout -b /tmp/build 
    -E ".*moc_.*" -E ".*automoc_dir.*"  -E ".*/GTestExternal/.*" -E "/usr/.*" ; echo DONE'

    
