# coding: utf-8

# flake8: noqa
"""
    DigitalRooster

    Open API for Digital Rooster  # noqa: E501

    The version of the OpenAPI document: 0.8.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.alarm import Alarm
from openapi_client.models.error import Error
from openapi_client.models.podcast import Podcast
from openapi_client.models.station import Station
